<?php

namespace ExpressPayments\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping =
        [
            \ExpressPayments\Collection::OBJECT_NAME => \ExpressPayments\Collection::class,
            \ExpressPayments\Issuing\CardDetails::OBJECT_NAME => \ExpressPayments\Issuing\CardDetails::class,
            \ExpressPayments\SearchResult::OBJECT_NAME => \ExpressPayments\SearchResult::class,
            \ExpressPayments\File::OBJECT_NAME_ALT => \ExpressPayments\File::class,
            // The beginning of the section generated from our OpenAPI spec
            \ExpressPayments\Account::OBJECT_NAME => \ExpressPayments\Account::class,
            \ExpressPayments\AccountLink::OBJECT_NAME => \ExpressPayments\AccountLink::class,
            \ExpressPayments\AccountSession::OBJECT_NAME => \ExpressPayments\AccountSession::class,
            \ExpressPayments\ApplePayDomain::OBJECT_NAME => \ExpressPayments\ApplePayDomain::class,
            \ExpressPayments\ApplicationFee::OBJECT_NAME => \ExpressPayments\ApplicationFee::class,
            \ExpressPayments\ApplicationFeeRefund::OBJECT_NAME => \ExpressPayments\ApplicationFeeRefund::class,
            \ExpressPayments\Apps\Secret::OBJECT_NAME => \ExpressPayments\Apps\Secret::class,
            \ExpressPayments\Balance::OBJECT_NAME => \ExpressPayments\Balance::class,
            \ExpressPayments\BalanceTransaction::OBJECT_NAME => \ExpressPayments\BalanceTransaction::class,
            \ExpressPayments\BankAccount::OBJECT_NAME => \ExpressPayments\BankAccount::class,
            \ExpressPayments\BillingPortal\Configuration::OBJECT_NAME => \ExpressPayments\BillingPortal\Configuration::class,
            \ExpressPayments\BillingPortal\Session::OBJECT_NAME => \ExpressPayments\BillingPortal\Session::class,
            \ExpressPayments\Capability::OBJECT_NAME => \ExpressPayments\Capability::class,
            \ExpressPayments\Card::OBJECT_NAME => \ExpressPayments\Card::class,
            \ExpressPayments\CashBalance::OBJECT_NAME => \ExpressPayments\CashBalance::class,
            \ExpressPayments\Charge::OBJECT_NAME => \ExpressPayments\Charge::class,
            \ExpressPayments\Checkout\Session::OBJECT_NAME => \ExpressPayments\Checkout\Session::class,
            \ExpressPayments\CountrySpec::OBJECT_NAME => \ExpressPayments\CountrySpec::class,
            \ExpressPayments\Coupon::OBJECT_NAME => \ExpressPayments\Coupon::class,
            \ExpressPayments\CreditNote::OBJECT_NAME => \ExpressPayments\CreditNote::class,
            \ExpressPayments\CreditNoteLineItem::OBJECT_NAME => \ExpressPayments\CreditNoteLineItem::class,
            \ExpressPayments\Customer::OBJECT_NAME => \ExpressPayments\Customer::class,
            \ExpressPayments\CustomerBalanceTransaction::OBJECT_NAME => \ExpressPayments\CustomerBalanceTransaction::class,
            \ExpressPayments\CustomerCashBalanceTransaction::OBJECT_NAME => \ExpressPayments\CustomerCashBalanceTransaction::class,
            \ExpressPayments\Discount::OBJECT_NAME => \ExpressPayments\Discount::class,
            \ExpressPayments\Dispute::OBJECT_NAME => \ExpressPayments\Dispute::class,
            \ExpressPayments\EphemeralKey::OBJECT_NAME => \ExpressPayments\EphemeralKey::class,
            \ExpressPayments\Event::OBJECT_NAME => \ExpressPayments\Event::class,
            \ExpressPayments\ExchangeRate::OBJECT_NAME => \ExpressPayments\ExchangeRate::class,
            \ExpressPayments\File::OBJECT_NAME => \ExpressPayments\File::class,
            \ExpressPayments\FileLink::OBJECT_NAME => \ExpressPayments\FileLink::class,
            \ExpressPayments\FinancialConnections\Account::OBJECT_NAME => \ExpressPayments\FinancialConnections\Account::class,
            \ExpressPayments\FinancialConnections\AccountOwner::OBJECT_NAME => \ExpressPayments\FinancialConnections\AccountOwner::class,
            \ExpressPayments\FinancialConnections\AccountOwnership::OBJECT_NAME => \ExpressPayments\FinancialConnections\AccountOwnership::class,
            \ExpressPayments\FinancialConnections\Session::OBJECT_NAME => \ExpressPayments\FinancialConnections\Session::class,
            \ExpressPayments\FundingInstructions::OBJECT_NAME => \ExpressPayments\FundingInstructions::class,
            \ExpressPayments\Identity\VerificationReport::OBJECT_NAME => \ExpressPayments\Identity\VerificationReport::class,
            \ExpressPayments\Identity\VerificationSession::OBJECT_NAME => \ExpressPayments\Identity\VerificationSession::class,
            \ExpressPayments\Invoice::OBJECT_NAME => \ExpressPayments\Invoice::class,
            \ExpressPayments\InvoiceItem::OBJECT_NAME => \ExpressPayments\InvoiceItem::class,
            \ExpressPayments\InvoiceLineItem::OBJECT_NAME => \ExpressPayments\InvoiceLineItem::class,
            \ExpressPayments\Issuing\Authorization::OBJECT_NAME => \ExpressPayments\Issuing\Authorization::class,
            \ExpressPayments\Issuing\Card::OBJECT_NAME => \ExpressPayments\Issuing\Card::class,
            \ExpressPayments\Issuing\Cardholder::OBJECT_NAME => \ExpressPayments\Issuing\Cardholder::class,
            \ExpressPayments\Issuing\Dispute::OBJECT_NAME => \ExpressPayments\Issuing\Dispute::class,
            \ExpressPayments\Issuing\Token::OBJECT_NAME => \ExpressPayments\Issuing\Token::class,
            \ExpressPayments\Issuing\Transaction::OBJECT_NAME => \ExpressPayments\Issuing\Transaction::class,
            \ExpressPayments\LineItem::OBJECT_NAME => \ExpressPayments\LineItem::class,
            \ExpressPayments\LoginLink::OBJECT_NAME => \ExpressPayments\LoginLink::class,
            \ExpressPayments\Mandate::OBJECT_NAME => \ExpressPayments\Mandate::class,
            \ExpressPayments\PaymentIntent::OBJECT_NAME => \ExpressPayments\PaymentIntent::class,
            \ExpressPayments\PaymentLink::OBJECT_NAME => \ExpressPayments\PaymentLink::class,
            \ExpressPayments\PaymentMethod::OBJECT_NAME => \ExpressPayments\PaymentMethod::class,
            \ExpressPayments\PaymentMethodConfiguration::OBJECT_NAME => \ExpressPayments\PaymentMethodConfiguration::class,
            \ExpressPayments\PaymentMethodDomain::OBJECT_NAME => \ExpressPayments\PaymentMethodDomain::class,
            \ExpressPayments\Payout::OBJECT_NAME => \ExpressPayments\Payout::class,
            \ExpressPayments\Person::OBJECT_NAME => \ExpressPayments\Person::class,
            \ExpressPayments\Plan::OBJECT_NAME => \ExpressPayments\Plan::class,
            \ExpressPayments\Price::OBJECT_NAME => \ExpressPayments\Price::class,
            \ExpressPayments\Product::OBJECT_NAME => \ExpressPayments\Product::class,
            \ExpressPayments\PromotionCode::OBJECT_NAME => \ExpressPayments\PromotionCode::class,
            \ExpressPayments\Quote::OBJECT_NAME => \ExpressPayments\Quote::class,
            \ExpressPayments\Radar\EarlyFraudWarning::OBJECT_NAME => \ExpressPayments\Radar\EarlyFraudWarning::class,
            \ExpressPayments\Radar\ValueList::OBJECT_NAME => \ExpressPayments\Radar\ValueList::class,
            \ExpressPayments\Radar\ValueListItem::OBJECT_NAME => \ExpressPayments\Radar\ValueListItem::class,
            \ExpressPayments\Refund::OBJECT_NAME => \ExpressPayments\Refund::class,
            \ExpressPayments\Reporting\ReportRun::OBJECT_NAME => \ExpressPayments\Reporting\ReportRun::class,
            \ExpressPayments\Reporting\ReportType::OBJECT_NAME => \ExpressPayments\Reporting\ReportType::class,
            \ExpressPayments\Review::OBJECT_NAME => \ExpressPayments\Review::class,
            \ExpressPayments\SetupAttempt::OBJECT_NAME => \ExpressPayments\SetupAttempt::class,
            \ExpressPayments\SetupIntent::OBJECT_NAME => \ExpressPayments\SetupIntent::class,
            \ExpressPayments\ShippingRate::OBJECT_NAME => \ExpressPayments\ShippingRate::class,
            \ExpressPayments\Sigma\ScheduledQueryRun::OBJECT_NAME => \ExpressPayments\Sigma\ScheduledQueryRun::class,
            \ExpressPayments\Source::OBJECT_NAME => \ExpressPayments\Source::class,
            \ExpressPayments\SourceTransaction::OBJECT_NAME => \ExpressPayments\SourceTransaction::class,
            \ExpressPayments\Subscription::OBJECT_NAME => \ExpressPayments\Subscription::class,
            \ExpressPayments\SubscriptionItem::OBJECT_NAME => \ExpressPayments\SubscriptionItem::class,
            \ExpressPayments\SubscriptionSchedule::OBJECT_NAME => \ExpressPayments\SubscriptionSchedule::class,
            \ExpressPayments\Tax\Calculation::OBJECT_NAME => \ExpressPayments\Tax\Calculation::class,
            \ExpressPayments\Tax\CalculationLineItem::OBJECT_NAME => \ExpressPayments\Tax\CalculationLineItem::class,
            \ExpressPayments\Tax\Registration::OBJECT_NAME => \ExpressPayments\Tax\Registration::class,
            \ExpressPayments\Tax\Settings::OBJECT_NAME => \ExpressPayments\Tax\Settings::class,
            \ExpressPayments\Tax\Transaction::OBJECT_NAME => \ExpressPayments\Tax\Transaction::class,
            \ExpressPayments\Tax\TransactionLineItem::OBJECT_NAME => \ExpressPayments\Tax\TransactionLineItem::class,
            \ExpressPayments\TaxCode::OBJECT_NAME => \ExpressPayments\TaxCode::class,
            \ExpressPayments\TaxId::OBJECT_NAME => \ExpressPayments\TaxId::class,
            \ExpressPayments\TaxRate::OBJECT_NAME => \ExpressPayments\TaxRate::class,
            \ExpressPayments\Terminal\Configuration::OBJECT_NAME => \ExpressPayments\Terminal\Configuration::class,
            \ExpressPayments\Terminal\ConnectionToken::OBJECT_NAME => \ExpressPayments\Terminal\ConnectionToken::class,
            \ExpressPayments\Terminal\Location::OBJECT_NAME => \ExpressPayments\Terminal\Location::class,
            \ExpressPayments\Terminal\Reader::OBJECT_NAME => \ExpressPayments\Terminal\Reader::class,
            \ExpressPayments\TestHelpers\TestClock::OBJECT_NAME => \ExpressPayments\TestHelpers\TestClock::class,
            \ExpressPayments\Token::OBJECT_NAME => \ExpressPayments\Token::class,
            \ExpressPayments\Topup::OBJECT_NAME => \ExpressPayments\Topup::class,
            \ExpressPayments\Transfer::OBJECT_NAME => \ExpressPayments\Transfer::class,
            \ExpressPayments\TransferReversal::OBJECT_NAME => \ExpressPayments\TransferReversal::class,
            \ExpressPayments\Treasury\CreditReversal::OBJECT_NAME => \ExpressPayments\Treasury\CreditReversal::class,
            \ExpressPayments\Treasury\DebitReversal::OBJECT_NAME => \ExpressPayments\Treasury\DebitReversal::class,
            \ExpressPayments\Treasury\FinancialAccount::OBJECT_NAME => \ExpressPayments\Treasury\FinancialAccount::class,
            \ExpressPayments\Treasury\FinancialAccountFeatures::OBJECT_NAME => \ExpressPayments\Treasury\FinancialAccountFeatures::class,
            \ExpressPayments\Treasury\InboundTransfer::OBJECT_NAME => \ExpressPayments\Treasury\InboundTransfer::class,
            \ExpressPayments\Treasury\OutboundPayment::OBJECT_NAME => \ExpressPayments\Treasury\OutboundPayment::class,
            \ExpressPayments\Treasury\OutboundTransfer::OBJECT_NAME => \ExpressPayments\Treasury\OutboundTransfer::class,
            \ExpressPayments\Treasury\ReceivedCredit::OBJECT_NAME => \ExpressPayments\Treasury\ReceivedCredit::class,
            \ExpressPayments\Treasury\ReceivedDebit::OBJECT_NAME => \ExpressPayments\Treasury\ReceivedDebit::class,
            \ExpressPayments\Treasury\Transaction::OBJECT_NAME => \ExpressPayments\Treasury\Transaction::class,
            \ExpressPayments\Treasury\TransactionEntry::OBJECT_NAME => \ExpressPayments\Treasury\TransactionEntry::class,
            \ExpressPayments\UsageRecord::OBJECT_NAME => \ExpressPayments\UsageRecord::class,
            \ExpressPayments\UsageRecordSummary::OBJECT_NAME => \ExpressPayments\UsageRecordSummary::class,
            \ExpressPayments\WebhookEndpoint::OBJECT_NAME => \ExpressPayments\WebhookEndpoint::class,
            // The end of the section generated from our OpenAPI spec
        ];
}
