<?php

namespace ExpressPlatby\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping =
        [
            \ExpressPlatby\Collection::OBJECT_NAME => \ExpressPlatby\Collection::class,
            \ExpressPlatby\Issuing\CardDetails::OBJECT_NAME => \ExpressPlatby\Issuing\CardDetails::class,
            \ExpressPlatby\SearchResult::OBJECT_NAME => \ExpressPlatby\SearchResult::class,
            \ExpressPlatby\File::OBJECT_NAME_ALT => \ExpressPlatby\File::class,
            // The beginning of the section generated from our OpenAPI spec
            \ExpressPlatby\Account::OBJECT_NAME => \ExpressPlatby\Account::class,
            \ExpressPlatby\AccountLink::OBJECT_NAME => \ExpressPlatby\AccountLink::class,
            \ExpressPlatby\AccountSession::OBJECT_NAME => \ExpressPlatby\AccountSession::class,
            \ExpressPlatby\ApplePayDomain::OBJECT_NAME => \ExpressPlatby\ApplePayDomain::class,
            \ExpressPlatby\ApplicationFee::OBJECT_NAME => \ExpressPlatby\ApplicationFee::class,
            \ExpressPlatby\ApplicationFeeRefund::OBJECT_NAME => \ExpressPlatby\ApplicationFeeRefund::class,
            \ExpressPlatby\Apps\Secret::OBJECT_NAME => \ExpressPlatby\Apps\Secret::class,
            \ExpressPlatby\Balance::OBJECT_NAME => \ExpressPlatby\Balance::class,
            \ExpressPlatby\BalanceTransaction::OBJECT_NAME => \ExpressPlatby\BalanceTransaction::class,
            \ExpressPlatby\BankAccount::OBJECT_NAME => \ExpressPlatby\BankAccount::class,
            \ExpressPlatby\BillingPortal\Configuration::OBJECT_NAME => \ExpressPlatby\BillingPortal\Configuration::class,
            \ExpressPlatby\BillingPortal\Session::OBJECT_NAME => \ExpressPlatby\BillingPortal\Session::class,
            \ExpressPlatby\Capability::OBJECT_NAME => \ExpressPlatby\Capability::class,
            \ExpressPlatby\Card::OBJECT_NAME => \ExpressPlatby\Card::class,
            \ExpressPlatby\CashBalance::OBJECT_NAME => \ExpressPlatby\CashBalance::class,
            \ExpressPlatby\Charge::OBJECT_NAME => \ExpressPlatby\Charge::class,
            \ExpressPlatby\Checkout\Session::OBJECT_NAME => \ExpressPlatby\Checkout\Session::class,
            \ExpressPlatby\CountrySpec::OBJECT_NAME => \ExpressPlatby\CountrySpec::class,
            \ExpressPlatby\Coupon::OBJECT_NAME => \ExpressPlatby\Coupon::class,
            \ExpressPlatby\CreditNote::OBJECT_NAME => \ExpressPlatby\CreditNote::class,
            \ExpressPlatby\CreditNoteLineItem::OBJECT_NAME => \ExpressPlatby\CreditNoteLineItem::class,
            \ExpressPlatby\Customer::OBJECT_NAME => \ExpressPlatby\Customer::class,
            \ExpressPlatby\CustomerBalanceTransaction::OBJECT_NAME => \ExpressPlatby\CustomerBalanceTransaction::class,
            \ExpressPlatby\CustomerCashBalanceTransaction::OBJECT_NAME => \ExpressPlatby\CustomerCashBalanceTransaction::class,
            \ExpressPlatby\Discount::OBJECT_NAME => \ExpressPlatby\Discount::class,
            \ExpressPlatby\Dispute::OBJECT_NAME => \ExpressPlatby\Dispute::class,
            \ExpressPlatby\EphemeralKey::OBJECT_NAME => \ExpressPlatby\EphemeralKey::class,
            \ExpressPlatby\Event::OBJECT_NAME => \ExpressPlatby\Event::class,
            \ExpressPlatby\ExchangeRate::OBJECT_NAME => \ExpressPlatby\ExchangeRate::class,
            \ExpressPlatby\File::OBJECT_NAME => \ExpressPlatby\File::class,
            \ExpressPlatby\FileLink::OBJECT_NAME => \ExpressPlatby\FileLink::class,
            \ExpressPlatby\FinancialConnections\Account::OBJECT_NAME => \ExpressPlatby\FinancialConnections\Account::class,
            \ExpressPlatby\FinancialConnections\AccountOwner::OBJECT_NAME => \ExpressPlatby\FinancialConnections\AccountOwner::class,
            \ExpressPlatby\FinancialConnections\AccountOwnership::OBJECT_NAME => \ExpressPlatby\FinancialConnections\AccountOwnership::class,
            \ExpressPlatby\FinancialConnections\Session::OBJECT_NAME => \ExpressPlatby\FinancialConnections\Session::class,
            \ExpressPlatby\FundingInstructions::OBJECT_NAME => \ExpressPlatby\FundingInstructions::class,
            \ExpressPlatby\Identity\VerificationReport::OBJECT_NAME => \ExpressPlatby\Identity\VerificationReport::class,
            \ExpressPlatby\Identity\VerificationSession::OBJECT_NAME => \ExpressPlatby\Identity\VerificationSession::class,
            \ExpressPlatby\Invoice::OBJECT_NAME => \ExpressPlatby\Invoice::class,
            \ExpressPlatby\InvoiceItem::OBJECT_NAME => \ExpressPlatby\InvoiceItem::class,
            \ExpressPlatby\InvoiceLineItem::OBJECT_NAME => \ExpressPlatby\InvoiceLineItem::class,
            \ExpressPlatby\Issuing\Authorization::OBJECT_NAME => \ExpressPlatby\Issuing\Authorization::class,
            \ExpressPlatby\Issuing\Card::OBJECT_NAME => \ExpressPlatby\Issuing\Card::class,
            \ExpressPlatby\Issuing\Cardholder::OBJECT_NAME => \ExpressPlatby\Issuing\Cardholder::class,
            \ExpressPlatby\Issuing\Dispute::OBJECT_NAME => \ExpressPlatby\Issuing\Dispute::class,
            \ExpressPlatby\Issuing\Token::OBJECT_NAME => \ExpressPlatby\Issuing\Token::class,
            \ExpressPlatby\Issuing\Transaction::OBJECT_NAME => \ExpressPlatby\Issuing\Transaction::class,
            \ExpressPlatby\LineItem::OBJECT_NAME => \ExpressPlatby\LineItem::class,
            \ExpressPlatby\LoginLink::OBJECT_NAME => \ExpressPlatby\LoginLink::class,
            \ExpressPlatby\Mandate::OBJECT_NAME => \ExpressPlatby\Mandate::class,
            \ExpressPlatby\PaymentIntent::OBJECT_NAME => \ExpressPlatby\PaymentIntent::class,
            \ExpressPlatby\PaymentLink::OBJECT_NAME => \ExpressPlatby\PaymentLink::class,
            \ExpressPlatby\PaymentMethod::OBJECT_NAME => \ExpressPlatby\PaymentMethod::class,
            \ExpressPlatby\PaymentMethodConfiguration::OBJECT_NAME => \ExpressPlatby\PaymentMethodConfiguration::class,
            \ExpressPlatby\PaymentMethodDomain::OBJECT_NAME => \ExpressPlatby\PaymentMethodDomain::class,
            \ExpressPlatby\Payout::OBJECT_NAME => \ExpressPlatby\Payout::class,
            \ExpressPlatby\Person::OBJECT_NAME => \ExpressPlatby\Person::class,
            \ExpressPlatby\Plan::OBJECT_NAME => \ExpressPlatby\Plan::class,
            \ExpressPlatby\Price::OBJECT_NAME => \ExpressPlatby\Price::class,
            \ExpressPlatby\Product::OBJECT_NAME => \ExpressPlatby\Product::class,
            \ExpressPlatby\PromotionCode::OBJECT_NAME => \ExpressPlatby\PromotionCode::class,
            \ExpressPlatby\Quote::OBJECT_NAME => \ExpressPlatby\Quote::class,
            \ExpressPlatby\Radar\EarlyFraudWarning::OBJECT_NAME => \ExpressPlatby\Radar\EarlyFraudWarning::class,
            \ExpressPlatby\Radar\ValueList::OBJECT_NAME => \ExpressPlatby\Radar\ValueList::class,
            \ExpressPlatby\Radar\ValueListItem::OBJECT_NAME => \ExpressPlatby\Radar\ValueListItem::class,
            \ExpressPlatby\Refund::OBJECT_NAME => \ExpressPlatby\Refund::class,
            \ExpressPlatby\Reporting\ReportRun::OBJECT_NAME => \ExpressPlatby\Reporting\ReportRun::class,
            \ExpressPlatby\Reporting\ReportType::OBJECT_NAME => \ExpressPlatby\Reporting\ReportType::class,
            \ExpressPlatby\Review::OBJECT_NAME => \ExpressPlatby\Review::class,
            \ExpressPlatby\SetupAttempt::OBJECT_NAME => \ExpressPlatby\SetupAttempt::class,
            \ExpressPlatby\SetupIntent::OBJECT_NAME => \ExpressPlatby\SetupIntent::class,
            \ExpressPlatby\ShippingRate::OBJECT_NAME => \ExpressPlatby\ShippingRate::class,
            \ExpressPlatby\Sigma\ScheduledQueryRun::OBJECT_NAME => \ExpressPlatby\Sigma\ScheduledQueryRun::class,
            \ExpressPlatby\Source::OBJECT_NAME => \ExpressPlatby\Source::class,
            \ExpressPlatby\SourceTransaction::OBJECT_NAME => \ExpressPlatby\SourceTransaction::class,
            \ExpressPlatby\Subscription::OBJECT_NAME => \ExpressPlatby\Subscription::class,
            \ExpressPlatby\SubscriptionItem::OBJECT_NAME => \ExpressPlatby\SubscriptionItem::class,
            \ExpressPlatby\SubscriptionSchedule::OBJECT_NAME => \ExpressPlatby\SubscriptionSchedule::class,
            \ExpressPlatby\Tax\Calculation::OBJECT_NAME => \ExpressPlatby\Tax\Calculation::class,
            \ExpressPlatby\Tax\CalculationLineItem::OBJECT_NAME => \ExpressPlatby\Tax\CalculationLineItem::class,
            \ExpressPlatby\Tax\Registration::OBJECT_NAME => \ExpressPlatby\Tax\Registration::class,
            \ExpressPlatby\Tax\Settings::OBJECT_NAME => \ExpressPlatby\Tax\Settings::class,
            \ExpressPlatby\Tax\Transaction::OBJECT_NAME => \ExpressPlatby\Tax\Transaction::class,
            \ExpressPlatby\Tax\TransactionLineItem::OBJECT_NAME => \ExpressPlatby\Tax\TransactionLineItem::class,
            \ExpressPlatby\TaxCode::OBJECT_NAME => \ExpressPlatby\TaxCode::class,
            \ExpressPlatby\TaxId::OBJECT_NAME => \ExpressPlatby\TaxId::class,
            \ExpressPlatby\TaxRate::OBJECT_NAME => \ExpressPlatby\TaxRate::class,
            \ExpressPlatby\Terminal\Configuration::OBJECT_NAME => \ExpressPlatby\Terminal\Configuration::class,
            \ExpressPlatby\Terminal\ConnectionToken::OBJECT_NAME => \ExpressPlatby\Terminal\ConnectionToken::class,
            \ExpressPlatby\Terminal\Location::OBJECT_NAME => \ExpressPlatby\Terminal\Location::class,
            \ExpressPlatby\Terminal\Reader::OBJECT_NAME => \ExpressPlatby\Terminal\Reader::class,
            \ExpressPlatby\TestHelpers\TestClock::OBJECT_NAME => \ExpressPlatby\TestHelpers\TestClock::class,
            \ExpressPlatby\Token::OBJECT_NAME => \ExpressPlatby\Token::class,
            \ExpressPlatby\Topup::OBJECT_NAME => \ExpressPlatby\Topup::class,
            \ExpressPlatby\Transfer::OBJECT_NAME => \ExpressPlatby\Transfer::class,
            \ExpressPlatby\TransferReversal::OBJECT_NAME => \ExpressPlatby\TransferReversal::class,
            \ExpressPlatby\Treasury\CreditReversal::OBJECT_NAME => \ExpressPlatby\Treasury\CreditReversal::class,
            \ExpressPlatby\Treasury\DebitReversal::OBJECT_NAME => \ExpressPlatby\Treasury\DebitReversal::class,
            \ExpressPlatby\Treasury\FinancialAccount::OBJECT_NAME => \ExpressPlatby\Treasury\FinancialAccount::class,
            \ExpressPlatby\Treasury\FinancialAccountFeatures::OBJECT_NAME => \ExpressPlatby\Treasury\FinancialAccountFeatures::class,
            \ExpressPlatby\Treasury\InboundTransfer::OBJECT_NAME => \ExpressPlatby\Treasury\InboundTransfer::class,
            \ExpressPlatby\Treasury\OutboundPayment::OBJECT_NAME => \ExpressPlatby\Treasury\OutboundPayment::class,
            \ExpressPlatby\Treasury\OutboundTransfer::OBJECT_NAME => \ExpressPlatby\Treasury\OutboundTransfer::class,
            \ExpressPlatby\Treasury\ReceivedCredit::OBJECT_NAME => \ExpressPlatby\Treasury\ReceivedCredit::class,
            \ExpressPlatby\Treasury\ReceivedDebit::OBJECT_NAME => \ExpressPlatby\Treasury\ReceivedDebit::class,
            \ExpressPlatby\Treasury\Transaction::OBJECT_NAME => \ExpressPlatby\Treasury\Transaction::class,
            \ExpressPlatby\Treasury\TransactionEntry::OBJECT_NAME => \ExpressPlatby\Treasury\TransactionEntry::class,
            \ExpressPlatby\UsageRecord::OBJECT_NAME => \ExpressPlatby\UsageRecord::class,
            \ExpressPlatby\UsageRecordSummary::OBJECT_NAME => \ExpressPlatby\UsageRecordSummary::class,
            \ExpressPlatby\WebhookEndpoint::OBJECT_NAME => \ExpressPlatby\WebhookEndpoint::class,
            // The end of the section generated from our OpenAPI spec
        ];
}
